### ISSUE TITLE
Symlinking log and tmp subdirectories

### ISSUE THREAD

**Issue by codyrobbins** [capistrano/rails#104]
I seem to remember previous versions of Capistrano symlinking the `log` directory and subdirectories of `tmp`:

* `cache`
* `pids`
* `sessions`
* `sockets`

It seems like `capistrano-rails` symlinks `public/assets` but doesn’t do automatically add `log` or any of the `tmp` subdirectories to `linked_dirs`.

Is this on purpose? It seems like you would always want `log` symlinked. I’m having a hard time finding any official information on which—if any—of these `tmp` subdirectories should be symlinked. If they’re supposed to be, then this gem should be doing so. If not, if someone can give me a quick explanation I can add some documentation so other people with the same question won’t be confused.

**Comment by mattbrictson** [comment]
If you run `cap install` on a Rails project it should create a `config/deploy.rb` that has these lines:

```
# Default value for linked_dirs is []
# set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'vendor/bundle', 'public/system')
```

So the code is there, but it is commented out by default. I think the authors of Capistrano 3 prefer to have fewer automatic defaults, meaning developers need to opt in.

**Comment by codyrobbins** [comment]
Yes, it does include that line in the deploy configuration template and it makes sense to leave that setting commented out in the default case since Capistrano can be used with non-Rails projects.

However, since this gem is specifically mean to integrate Rails with Capistrano, and since you’re going to want to symlink those directories in ninety-nine percent of Rails deployments, it makes sense (to me at least) that this gem should be adding them as part of its default behavior to reduce the verbosity of the deployment configuration.

In any case, it’s inconsistent right now because `public/assets` is added but `log` and the `tmp` directories aren’t. If no defaults are going to be provided (which I disagree with), then `public/assets` shouldn’t be set. If defaults are going to be provided, then `log` and the `tmp` directories should be added as well.

**Comment by boosty** [comment]
:+1:

**Comment by runephilosof** [comment]
The log folder definitely needs to be symlinked.
But why would the other folders need to be symlinked?

**Comment by codyrobbins** [comment]
@runephilosof I couldn’t really find any official information regarding whether they should be symlinked or not, but I seem to remember previous versions of Capistrano doing so.

**Comment by mattbrictson** [comment]
@runephilosof @codyrobbins Here are some reasons for linking those directories:

* `public/assets` – in a rolling deployment scenario, some customers may be referencing old asset versions (stylesheets, images, etc.) while other customers reference the new versions. Using a shared assets directory ensures that old versions and new versions reside in the same place and are accessible by the web server.
* `tmp/cache` – The asset compilation step of deployment is really slow if it has to start from scratch. Using a shared tmp directory means the compilation step can reuse cached artifacts from past compilations, speeding up deployment.
* `tmp/{pids,sockets}` – Used by unicorn (and perhaps other servers) to manage server state. During a deploy, the server is pointing at an old version and then switches to the newly deployed version, potentially without a cold stop/start of the server processes. Keeping the pid and socket files in a shared location facilitates this kind of zero downtime deployment.
* `public/system` – Historically, uploaded file attachments are stored here. If this directory isn't shared, all uploaded files would effectively disappear every time a new version of the app is deployed.

**Comment by codyrobbins** [comment]
@mattbrictson Thanks! So it sounds like all these should indeed be symlinked by `capistrano-rails` by default. Good catch with `public/system`, too. And I think `tmp/sessions` stores session data when using the file-based session mechanism so presumably that should be symlinked as well.

**Comment by mattbrictson** [comment]
@codyrobbins OK but if you aren't using unicorn or file-based session storage, then you'd be stuck with a bunch of empty symlinked dirs you don't need? Just playing devil's advocate. :smiling_imp:

**Comment by codyrobbins** [comment]
@mattbrictson A stock Rails app is already chock full of empty directories and tons of files you don’t need right from the start :) I think it makes way more sense that this plugin works out of the box for all use cases. If the expense is a few unused symlinks I don’t think that’s any appreciable cost. Again, if it’s going to symlink `public/assets` then I think it should be consistent and symlink everything.

**Comment by rzane** [comment]
Maybe this should be added to the readme? I think I always deleted that linked_dirs line. Whoops!

**Comment by kirs** [comment]
@codyrobbins:
> Is this on purpose?

Yes, because linking these files is suggested in default generated `deploy.rb` and everyone who's setting git repo URL, app path and other variables is supposed to notice it.

Adding these paths to `linked_dirs` and `linked_files` automatically may be unexpected behaviour.
I will add a note to README in this repo.

Thanks for such a suggestion :yellow_heart:

**Comment by codyrobbins** [comment]
Thanks for your reply!

> Adding these paths to linked_dirs and linked_files automatically may be unexpected behaviour

Could you clarify? How so? It still seems to me like *not* including them is unexpected behavior.

> is supposed to notice it

People are supposed to do lots of things. The point of this plugin is to make it easier for people to deploy Rails with Capistrano using fewer magic incantations. It would be far preferable if the plugin just covered the normal use case by default so ninety-nine percent of people don't have to notice an obscure comment in the configuration file.

> I will add a note to README in this repo

Thanks! This is better than nothing, but, again, I feel like people deviating from the default use case should be the ones expected to notice the configuration comments and scour the readme.

You didn’t really address why this behavior is inconsistent with respect to `public/assets`. I’m happy to put together the pull request for this—I’d love to make this plugin “just work” for the base case and I feel like the current behavior prevents that.
