### ISSUE TITLE
Mysql2::Error: Access denied for user root   using password: NO)

### ISSUE THREAD

**Issue by erwin16** [capistrano/rails#106]
I trying to deploy a Rails application to AWS EC2 instance , mySQL db on AWS-RDS instance 
tasks are executing fine until the db:migrate task which is using  'root'@'172.31.11.0' (using password: NO)   172.31.11.0 being the internal EC2 IP address 

	===error log =======
	DEBUG[5e745929] Running /usr/bin/env if test ! -d /srv/simpleapp/releases/20150213170350; then echo "Directory does not exist '/srv/simpleapp/releases/20150213170350'" 1>&2; false; fi on 54.93.110.117
	DEBUG[5e745929] Command: if test ! -d /srv/simpleapp/releases/20150213170350; then echo "Directory does not exist '/srv/simpleapp/releases/20150213170350'" 1>&2; false; fi
	DEBUG[5e745929] Finished in 0.130 seconds with exit status 0 (successful).
	INFO[2dc72ed6] Running RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.0 ~/.rbenv/bin/rbenv exec bundle exec rake db:migrate on 54.93.110.117
	DEBUG[2dc72ed6] Command: cd /srv/simpleapp/releases/20150213170350 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.0 RAILS_ENV=staging RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.0 ~/.rbenv/bin/rbenv exec bundle exec rake db:migrate )
	DEBUG[2dc72ed6] 	rake aborted!
	DEBUG[2dc72ed6] 	Mysql2::Error: Access denied for user 'root'@'172.31.11.0' (using password: NO)
	DEBUG[2dc72ed6] 	/srv/simpleapp/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
	DEBUG[2dc72ed6] 	/srv/simpleapp/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
	DEBUG[2dc72ed6] 	/srv/simpleapp/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
	..
	=== 

previous tasks uploading the dtabase.yml and .env  were successful

    INFOUploading config config/database.staging.yml as config/database.yml
    INFOUploading config ./.env.staging as .env

so all db credentials are uploaded   ( host, db name, user, password )

**Comment by kirs** [comment]
Please, check out configuration of your DB and app server.
Failed database connection has no clue to capistrano-rails.
