### ISSUE TITLE
Allow modification of rake command

### ISSUE THREAD

**Issue by scottrobertson** [capistrano/rails#108]
Hey,

I use foreman, and because of that, when running db:migrate i must prepend it with `bundle exec foreman run` so that it picks up the correct .env file. 

My question is, could you allow us to override the command used to run db:migrate similar to how it's done with here: https://github.com/javan/whenever/blob/master/lib/whenever/capistrano/v3/tasks/whenever.rake (See `set :whenever_command`).

Thanks
Scott

**Comment by kirs** [comment]
You can use SSHKit API to replace the commands:

```
SSHKit.config.command_map.prefix[:rake].unshift("prepend_your_rake command")
```

Check out how it's done with Bundler to prefix all the commands with `bundle exec`: https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/bundler.cap#L49
