### ISSUE TITLE
Capistrano: cap:check “acts” like it doesn't find the username for the server auth

### ISSUE THREAD

**Issue by benams** [capistrano/rails#120]
I'm trying to set capistrano (v. 3.4.0) to handle the deployment process of my rails application. When I execute cap `deploy:check` to test the connection I'm asked to type a password to a server with no username: "@10.0.0.150's password: "

Here is my deploy.rb file:

```ruby
# Server settings
set :user, "deploy"
server "10.0.0.150", roles: [:app, :web, :db], primary: true
set :deploy_to, '/applications/candiru-gateway/'
set :use_sudo, false
set :deploy_via, :copy
```

Any idea why the user deploy doesn't show up when I'm asked to enter the password?

**Comment by mattbrictson** [comment]
The settings you have in your example look like Capistrano 2.x settings. Versions 2.x and 3.x are completely different and require different settings in the `deploy.rb`. I suggest running `bundle exec cap install`, which will generate a sample `deploy.rb` for you to follow. Or you can look at the samples here: https://github.com/capistrano/capistrano/tree/master/lib/capistrano/templates

**Comment by will-in-wi** [comment]
@benams Is this still an issue for you?
