### ISSUE TITLE
Tar's warning when do rollback

### ISSUE THREAD

**Issue by lancedikson** [capistrano/rails#121]
Hello,

I get some warning when ran `bundle exec cap staging deploy:rollback`:

```
INFO [5ee1a692] Running /usr/bin/env tar -czf /opt/apps/adrenaline-server/rolled-back-release-20150511124109.tar.gz /opt/apps/adrenaline-server/releases/20150511124109 as deploy@dev.stv.ru
DEBUG [5ee1a692] Command: /usr/bin/env tar -czf /opt/apps/adrenaline-server/rolled-back-release-20150511124109.tar.gz /opt/apps/adrenaline-server/releases/20150511124109
DEBUG [5ee1a692] 	tar:
DEBUG [5ee1a692] 	Removing leading `/' from member names
DEBUG [5ee1a692]
INFO [5ee1a692] Finished in 2.369 seconds with exit status 0 (successful).
```

It isn't break the rollback process, but I worry about it :) So, do you have any ideas why I got this message?

**Comment by lancedikson** [comment]
So, I use capistrano (3.2.1) and capistrano-rails (1.1.3)

**Comment by will-in-wi** [comment]
@lancedikson Is this still the case in the latest Capistrano/Capistrano-Rails?

**Comment by lancedikson** [comment]
@will-in-wi, I don't know because of I left the project about 6 months ago. So, I even can't test it now. I think you would close the issue and somebody will reopen it if run into the bug.

**Comment by will-in-wi** [comment]
Thanks for the response @lancedikson! I'll poke the maintainers to close this ticket.

@mattbrictson ?

**Comment by lancedikson** [comment]
I can do it now :)
