### ISSUE TITLE
backup_manifest fails when multiple manifest files are detected

### ISSUE THREAD

**Issue by mzaccari** [capistrano/rails#123]
Using `rails 3.2`, `capistrano 3.4.0` and `capistrano-rails 1.1.3`

Precompiling the assets works fine, but `backup_manifest` consistently fails due to having two manifest files (`manifest.json` and `manifest.yml`). When `detect_manifest_path` runs it will return a string as:

```ruby
"/home/deployer/releases/20150608160111/public/assets/manifest.json\n/home/deployer/releases/20150608160111/public/assets/manifest.yml"
```

The error occurs when `cp` attempts to move the files and fails due to the "\n" between the file paths. I updated the method in my local gem to use `gsub(/\s+/, ' ')` before the strip and the deployment worked:

```ruby
    def detect_manifest_path
      %w(
        .sprockets-manifest*
        manifest*.*
      ).each do |pattern|
        candidate = release_path.join('public', fetch(:assets_prefix), pattern)
        return capture(:ls, candidate).gsub(/\s+/, ' ').strip if test(:ls, candidate)
      end
      msg = 'Rails assets manifest file not found.'
      warn msg
      fail Capistrano::FileNotFound, msg
    end
```

**Comment by alexagranov** [comment]
Right, same here.  This scenario is occurring due to a previous manifest.yml from a Rails 3.2.x build and I'm now deploying the first Rails 4.1.x build that employs updated sprockets, which uses the manifest-*.json format.

+1

**Comment by dustmoo** [comment]
+1 I had a mainfiests file for chrome in the source... it definitely got confused.

**Comment by ideaoforder** [comment]
+1

**Comment by will-in-wi** [comment]
This seems like a dup of https://github.com/capistrano/rails/issues/132 which was fixed in https://github.com/capistrano/rails/pull/133. Can this be closed?

**Comment by mattbrictson** [comment]
Please re-open if this issue persists after upgrading to the latest capistrano-rails.

**Comment by stiig** [comment]
Hello, I have the same issue, I have two manifest files, first is mine and second from rails_admin. An error appeared in https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/assets.rake#L93 because it fails when multiple files checked `[[ -f source_file && -f file1 file2 ]]`

I tried to fix it like this: 
```
if test "[[ -f #{source} && -f #{target.split.join(' && -f ')} ]]"
```
but this gives error in https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/assets.rake#L94 which target is multiple file path `file1 file2`
