### ISSUE TITLE
asset cache entries generated in one release folder are not usable by another release (with sprockets 3.x)

### ISSUE THREAD

**Issue by bughit** [capistrano/rails#130]
rails 4.2.3, ruby 2.2.2, sprockets 3.2.x

evidently the full asset path is used to produce the asset cache key

so if you run assets:precompile in release1 the generated cache is not usable in release2 even though shared

so how can you actually reuse the cache?

**Comment by bughit** [comment]
looks like sprockets 3.3.0 addresses this by using relative paths

**Comment by bughit** [comment]
but 3.3.0 has other problems (https://github.com/rails/sprockets/issues/96)

**Comment by bughit** [comment]
sprockets 2.12.4 works

**Comment by baburdick** [comment]
Any update to this?

**Comment by mattbrictson** [comment]
I don't understand the issue. Can you elaborate?

By default the Sprockets cache is placed in `<rails root>/tmp/cache/assets`, so as long as you are symlinking `tmp/cache` in Capistrano you should be good.

**Comment by will-in-wi** [comment]
This seems like a sprockets bug in an older version of sprockets. Sprockets 3.7 is out, and 4.0 is being worked on. Is this still an issue?

**Comment by will-in-wi** [comment]
Given that this ticket hasn't had activity for a year, and the Sprockets landscape has changed quite a bit since then, I'm closing this ticket. If anyone can reproduce, feel free to reopen.
