### ISSUE TITLE
deploy:assets:backup_manifest fails on cp - newline in file name

### ISSUE THREAD

**Issue by januszm** [capistrano/rails#132]
```bash
cp: missing destination file operand after `/path_to_release/public/assets/manifest-9e1685318bd6192a208c010fc829fc89.json\r'
```

Notice ```\r``` after .json . It breaks the command which attempts to copy files to assets_manifest_backup directory.

Bug in ```detect_manifest_path``` ? It returns in my case:

```
"#{release_path}/public/assets/manifest-9e1685318bd6192a208c010fc829fc89.json\r\n#{release_path}/public/assets/manifest.yml"
```

See \r there? between paths to fingerprinted and clean manifest file

Related to this great article? http://mywiki.wooledge.org/ParsingLs  :suspect:

UPDATE:

bad commit: a56cae3b0f29f3fffd55e48687b8360175eba291
Don't capture results from LS , previous version used a simple string with asterisk

```
release_path.join('public', fetch(:assets_prefix), 'manifest*.*')
```

**Comment by januszm** [comment]
Here's a quick fix: https://github.com/capistrano/rails/pull/133

**Comment by gamut** [comment]
Fixed it for me.  So how long does something like this take to make it into the project?  I would call this a rather critical bug.

**Comment by mcfiredrill** [comment]
While @januszm 's fix works, is there an underlying issue here? Are you supposed to have more than one manifest file?

**Comment by januszm** [comment]
Ha!, why it happens (ie. you have more than one manifest file) is a different story, but it may happen.

**Comment by openscript** [comment]
Run into the same problem after updating from 1.1.3 to 1.1.5.
Thank you @januszm for the quick fix.

**Comment by aliaksandrb** [comment]
Face the same problem during hackathon today, made me crazy while investigating :'(

**Comment by tlindsay** [comment]
This spontaneously started happening to me about a week ago. Doesn't happen to other developers on my team. How is that possible?

**Comment by will-in-wi** [comment]
It sounds like this can be closed as https://github.com/capistrano/rails/pull/133 was merged.
