### ISSUE TITLE
commit a002711f9 killed Rails 3 app deploy

### ISSUE THREAD

**Issue by cernyjakub** [capistrano/rails#142]
`rake assets:clean` removes ALL assets in rails 3, so now capistrano deletes the whole assets folder after compiling assets, which makes deploy of Rails 3 app unusable.

I propose adding some flag/switch to disable this if needed.

**Comment by igor-alexandrov** [comment]
Confirmed on rails-3.2.22 and ruby-2.2.3.

**Comment by exterm** [comment]
+1

**Comment by jbwl** [comment]
+1

**Comment by kirs** [comment]
Thanks for the report. Now fixed in master
