### ISSUE TITLE
v1.1.5 breaks deploy:symlink:linked_dirs

### ISSUE THREAD

**Issue by baburdick** [capistrano/rails#144]
When I attempt to deploy using `v1.1.5` and `set :keep_assets, 4`, `deploy:symlink:linked_dirs` fails trying to create a symlink where an existing directory or symlink already exists. Downgrading to `v1.1.3` (I didn't try `v1.1.4`) resolves the issue.
```
** Execute deploy:symlink:linked_dirs
INFO [6fcc0dc9] Running /usr/bin/env mkdir -p /var/www/my_app/releases/20151014224928 /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/public on staging1
DEBUG [6fcc0dc9] Command: umask 002 && /usr/bin/env mkdir -p /var/www/my_app/releases/20151014224928 /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/tmp /var/www/my_app/releases/20151014224928/public
DEBUG [6fcc0dc9] 	mkdir: cannot create directory `/var/www/my_app/releases/20151014224928/public': File exists
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host staging1: mkdir exit status: 1
mkdir stdout: mkdir: cannot create directory `/var/www/my_app/releases/20151014224928/public': File exists
mkdir stderr: Nothing written
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: mkdir: cannot create directory `/var/www/my_app/releases/20151014224928/public': File exists
mkdir stderr: Nothing written
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
~/.rvm/gems/ruby-2.1.2@my_app/gems/capistrano-3.4.0/lib/capistrano/tasks/deploy.rake:101:in `block (4 levels) in <top (required)>'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
~/.rvm/gems/ruby-2.1.2@my_app/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:symlink:linked_dirs
The deploy has failed with an error: Exception while executing on host staging1: mkdir exit status: 1
mkdir stdout: mkdir: cannot create directory `/var/www/my_app/releases/20151014224928/public': File exists
mkdir stderr: Nothing written
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by mattbrictson** [comment]
@baburdick v1.1.4 changed how the `:linked_dirs` value is set. It will now always append `public/assets` to the list of linked directories, even if you explicitly set it otherwise in `deploy.rb`. Are you doing anything like `set :linked_dirs, …` in your `deploy.rb`?

If you want to prevent capistrano-rails from automatically altering your `:linked_dirs`, I think you'll have to do it like this:

```ruby
task :override_linked_dirs do
  set :linked_dirs, %w(log tmp/pids tmp/sockets)
end
# Execute *after* capistrano-rails, so dirs won't be further altered
after "deploy:set_linked_dirs", :override_linked_dirs
```

**Comment by baburdick** [comment]
We do do that:
```ruby
set :linked_dirs, %w{log tmp/pids tmp/cache tmp/sessions tmp/sockets}
```
Was this deprecated at some point? I missed that. If not, it seems this change should have warranted at least a minor version bump, not just a patch version bump.

What was the change in v1.1.4 intended to accommodate? Is there something I can tweak in the asset pipeline or sprockets instead to accommodate that? The fix you recommend feels like I'm working around a bug in capistrano, or a conflict with the asset pipeline or sprockets.

If there's no other way, I'll do it. But this seems wrong.

**Comment by mattbrictson** [comment]
The change was introduced by #125.

I think the assumption is that all projects that use `capistrano/rails/assets` will want to have `public/assets` symlinked.

Pre-1.1.4, the way this was accomplished was that capistrano-rails would initialize `:linked_dirs` to `["public/assets"]`, and then as a developer, your responsibility would be to *add to that list*, as explained in the README, like this:

```ruby
set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache')
```

Thus ensuring that `public/assets` would remain in the list.

Starting with 1.1.4, this process has been reversed: you set `:linked_dirs` first, and then capistrano-rails adds to it. The end result was intended to be the same: `public/assets` is always in the list.

Your case is an edge case that is not well supported. In your case, you *don't* want `public/assets` in the `:linked_dirs` list (correct me if I'm wrong). So unfortunately you have to do a workaround.

I agree this should have been better documented. The side-effects of #125 were probably just overlooked.

**Comment by baburdick** [comment]
Ah. I had missed the lore about pushing onto `:linked_dirs` rather than setting it outright when I initially set up my `config/deploy.rb`. I never really wanted to avoid linking `public/assets`. It was more an unwelcome side-effect of me missing that lore. Looks like I'll be able to solve my nagging problem of one giant freshly-deployed `public/assets` directory per release. Thanks!

**Comment by baburdick** [comment]
Thanks. That seems to have solved it.
