### ISSUE TITLE
Handling DB migrations for mountable engines (proposal)

### ISSUE THREAD

**Issue by unabl4** [capistrano/rails#154]
If you use mountable engines in your Rails application then before running the 'db:migrate' rake task you need to first 'copy' the db migration files from engine(s).

This can be done by running `railties:install:migrations` rake task.
By default this gem does not do that, however you can manually hook it to the deploy flow chain.

For my projects I do it like this: 
`before 'deploy:migrate', 'railties:install:migrations'`

My proposal is to make it a default functionality of this gem.
If approved - I can implement it and make a pull request. :)

**Comment by mattbrictson** [comment]
Thanks for the proposal! Unfortunately I have no experience with `railties:install:migrations`, so I would not feel comfortable merging something like that in as default behavior. My suggestion would be to package this up as a separate gem and publish it to rubygems. We could then mention it in the README of capistrano-rails for people looking for this feature.

**Comment by will-in-wi** [comment]
I'd be concerned about doing this because I see it as fairly common practice to run `rake app:install:migrations` and commit the result, at which point we wouldn't want this to run.

However, it wouldn't be a bad idea to add it to the docs or the wiki!

**Comment by will-in-wi** [comment]
In thinking about this more, I think that the rake task to copy over DB migrations also assigns a timestamp to them, which is needed to ordering, particularly in relation to the containing app migrations. I don't think this is something that this is something Capistrano::Rails can handle.
