### ISSUE TITLE
no matches found: assets:clean[N]

### ISSUE THREAD

**Issue by cweilemann** [capistrano/rails#155]
I'm trying to remove N old assets from my project, but I'm continually running into:

`no matches found: assets:clean[N]`

When I perform the exact cap command manually, with N = 1:

`cd /var/www/app/releases/20151204031213 && ( export RAILS_ENV="staging" ; /var/www/app/rvm1scripts/rvm-auto.sh ruby-2.1.6@app ~/.rvm/bin/rvm default do bundle exec rake assets:clean[1]`

I get the same error.  However, if I run the above, replacing `assets:clean[1]` with `-vT`, I can see the `assets:clean[keep]` command.

Am I missing something trivial?

**Comment by mattbrictson** [comment]
Are you using zsh on the server? If so, you're probably running into the problem fixed in #150 (not merged yet).

**Comment by cweilemann** [comment]
Your assumption is spot on!  Sorry to bother you guys. Thanks!
