### ISSUE TITLE
undefined method `verbosity' for "/usr/bin/env deploy:migrating

### ISSUE THREAD

**Issue by dhughesbc** [capistrano/rails#170]
I am trying to use the migrations task but getting an error. In my Capfile when I uncomment this line:
``` 
require 'capistrano/rails/migrations''
```
I get this error:
```
** Execute deploy:migrate
 INFO [deploy:migrate] Run `rake db:migrate`
cap aborted!
undefined method `verbosity' for "/usr/bin/env deploy:migrating\n":String
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/formatters/pretty.rb:10:in `write'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/backends/printer.rb:14:in `block in execute'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/backends/printer.rb:13:in `tap'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/backends/printer.rb:13:in `execute'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capistrano-rails-1.1.6/lib/capistrano/tasks/migrations.rake:14:in `block (3 levels) in <top (required)>'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/dhughes/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:migrate
The deploy has failed with an error: undefined method `verbosity' for "/usr/bin/env deploy:migrating\n":String
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```
When I google it, in responses I see lot's of "Invoke should not be used inside the on() block." and it does indeed appear that migrate task does exactly that (line 14):
https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/migrations.rake#L7-L16

**Comment by mattbrictson** [comment]
That's a really old version of SSHKit. Have you tried upgrading to see if that fixes it?

**Comment by dhughesbc** [comment]
I can try. I do not have sshkit in my Gemfile. This is in my Gemfile.lock:
```
    capistrano (3.4.1)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
```

**Comment by mattbrictson** [comment]
Then `bundle update sshkit` should do the trick.

**Comment by dhughesbc** [comment]
Thanks for the quick response, but that did not install anything new.

**Comment by mattbrictson** [comment]
Hm. Are there any other lines mentioning `sshkit` in your Gemfile.lock? Something is preventing the upgrade, apparently.

You can also try running `bundle outdated sshkit` to see what the restriction is.

**Comment by dhughesbc** [comment]
Ok, turns out I had 'net-ssh' locked at an oldish version in my Gemfile `gem 'net-ssh', '~> 2.6.5'`. I bumped that to `2.8.0` to match https://github.com/capistrano/sshkit/blob/master/sshkit.gemspec and that seems to have fixed it. Thanks. 

For posterity, this came about from what I thought would be a simple capistrano 2 -> 3 upgrade using http://capistranorb.com/documentation/upgrading/. Maybe that guide should be updated to specify a newer version of 3.x? (curently shows 3.0). I see from https://github.com/capistrano/capistrano/commit/60ed6a32f053560792d9fd903631f9d92940aa22#diff-6766dd451c77d30f645bdd6b4542a39d that the sshkit dependency was updated a while ago, but using the guide I ended up with capistrano 3.4.1, which appears to have the mismatch in sshkit versions.

**Comment by mattbrictson** [comment]
Glad to hear the problem is resolved.

My suggestion would be that unless your project uses net-ssh explicitly, you should not have `gem "net-ssh"` in your Gemfile. Locking a transitive dependency like that may inadvertently prevent you from getting newer versions of SSHKit in the future.

Regarding the documentation, I'd be happy to accept a PR to make the upgrade guide a bit more up-to-date. Even small corrections are helpful. https://github.com/capistrano/documentation
