### ISSUE TITLE
`bundle exec` not being prefixed to `rake`

### ISSUE THREAD

**Issue by reedlaw** [capistrano/rails#174]
I have in `Capfile`:
```
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
```

But I get:
```
INFO [1770a042] Running /usr/bin/env rake assets:precompile on example.com
DEBUG [1770a042] Command: cd /.../20160530022301 && ( RAILS_ENV=production /usr/bin/env rake assets:precompile )
```

I can workaround by setting `SSHKit.config.command_map[:rake] = "bundle exec rake"` but shouldn't `bundle exec` be set by requiring `capistrano/bundler`?

**Comment by mattbrictson** [comment]
You're right: it should be handling `bundle exec rake` for you by virtue of requiring `capistrano/bundler` in your Capfile. I'm not sure why this isn't working.

Can you show me what gem versions you are using? (If you are on Capistrano 3.5.0, you can run `cap production doctor` to get this info.)

E.g. here is mine:

    capistrano         3.5.0
    airbrussh          1.0.2
    rake               10.5.0 (update available)
    sshkit             1.10.0
    capistrano-bundler 1.1.4
    capistrano-harrow  0.5.1
    capistrano-rails   1.1.6

**Comment by reedlaw** [comment]
I'm on Capistrano 3.0.1. I just upgraded and the problem has been fixed. Thanks!
