### ISSUE TITLE
What's the rationale behind migrating on the DB server, instead of APP server?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [capistrano/rails#181]
I was thinking about this recently. If you have a DB server, you probably don't want/have rails on it at all.
You want to target the database directly with some queries/tools, but you can't migrate on the db server.

So here is my question: shouldn't all the tasks run on `:app` instead? The migration logic is handled by rails, which is on the app server. Obviously the app server can connect to the db server, but having the need of installing rails in the db server seems really counter-intuitive.

**Comment by mattbrictson** [comment]
100% agree. I think the only reason it is set to `:db` is for backwards compatibility. If we change the default to `:app` it could break existing deployments.

**Comment by Fire-Dragon-DoL** [comment]
I imagine a major version change won't be enough? (there is still the configuration option if you want to revert this, which is how I'm dealing with it currently)

**Comment by mattbrictson** [comment]
We could do this with a major version bump, but I am not sure it is worth the upgrade pain that we might inflict on users. I consider this gem to be in maintenance mode and don't want to change things without a significant upside.

I would accept a PR to change to the README, though, to guide people in the right direction.

**Comment by Fire-Dragon-DoL** [comment]
That seems reasonable, README update is ok, I'll provide a PR

**Comment by mattbrictson** [comment]
Fixed by #182
