### ISSUE TITLE
Rename this repository so we can use Travis CI?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/rails#197]
Apparently [Travis blacklists all repositories named "rails"](https://github.com/travis-ci/travis-ci/issues/6907) (except for `rails/rails`, of course). That means we can never use Travis CI on this project unless we rename the repository. 😞 

We don't currently have any tests, so I guess it is not a big loss at the moment. But eventually I'd like to have automated tests, and more immediately, it would be nice to have Travis run [Danger](http://danger.systems) to automatically check pull requests for proper CHANGELOG entries (like we do for the other Capistrano repositories).

Something to think about. How much trouble would renaming the repository cause?

**Comment by will-in-wi** [comment]
My gut reaction is that blacklisting all test suites named "rails" is really draconian. I'd start by pushing back.

Worst case, a name like "cap-rails" or something might be okay. But it might break anyone's deployment who for some reason is hitting this repo directly.

**Comment by mattbrictson** [comment]
I received confirmation from Travis support that this rule should be lifted soon, possibly as early as next week. 👍
