### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rustygeldmacher** [capistrano/rails#203]
Hi everyone -- greatly appreciate capistrano-rails, it makes our lives much easier. Thanks!

Was wondering if there are plans to tag a new release soon? We need the ability that was added in https://github.com/capistrano/rails/pull/135 and would like to use an official release rather than a GitHub pointer.

Thanks again!

**Comment by mattbrictson** [comment]
Sorry! This should have been released a long time ago but somehow I dropped the ball. I'll publish one shortly.

**Comment by rustygeldmacher** [comment]
Thanks @mattbrictson, truly appreciate it!

**Comment by mattbrictson** [comment]
🚢 https://github.com/capistrano/rails/releases/tag/v1.3.0
