### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [capistrano/rails#205]
The "capistrano-rails" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems and in a gemspec.

**Comment by will-in-wi** [comment]
Good point. @mattbrictson any reason not to merge https://github.com/capistrano/rails/pull/206 ?

**Comment by will-in-wi** [comment]
@mensfeld This will be fixed in the next release of Capistrano::Rails.

**Comment by mensfeld** [comment]
@will-in-wi good afternoon. Any plans on a next release with this? :-) I really like to have a no non-licence gems in the projects I use or work with. Thank you and sorry for bothering.

**Comment by mattbrictson** [comment]
Thanks for the reminder! I'll do a release today.

**Comment by mensfeld** [comment]
@mattbrictson will ping you if that does not happen. I use a gem checking app and it adds me a warning each time I bundle with capistrano-rails :dagger:

**Comment by mattbrictson** [comment]
https://rubygems.org/gems/capistrano-rails/versions/1.3.1

**Comment by mensfeld** [comment]
@mattbrictson marked as resolved after gem bump: thank you. Marked as resolved on our side as well :-)

![resolved issue](https://i.imgur.com/zSJYlbk.png)
