### ISSUE TITLE
Staging environment booting in production mode. 

### ISSUE THREAD

**Issue by alosada** [capistrano/rails#225]
Hello!

I'm trying to deploy a rails 5 app to a staging server using capistrano with nginx and passenger, however running Rails.env yields production instead of staging. Here's my capistrano setup:

in config/deploy.rb:

```
set :stages, %i(staging production)
set :default_stage, :staging
```

in config/environments/staging.rb:

```
set :stage, :staging
set :rails_env, :staging
```

running `echo $RAILS_ENV` in my server yields 'staging'

and my passenger_app_env config aso has staging as value

I'm not aware of anything that could override those, Any ideas?

Thanks in advance.

PD: I'm using rbenv
PPD: Disclaimer: Asked in StackOverflow first!

**Comment by alosada** [comment]
nothing? :(

**Comment by FernE97** [comment]
Ran into this same issue and it was because the environment was being set to production inside `/etc/environment` on the server.

`sudo vim /etc/environment`

change to...

```
RAILS_ENV=staging
```
