### ISSUE TITLE
Asset cleanup

### ISSUE THREAD

**Issue by chubchenko** [capistrano/rails#251]
First of all thanks for your work :tada:

What do u think about specifying a default value for a `keep_assets` value based on the `keep_releases` value?

I'm wondering about it because I have performed a `cap doctor` and the `keep_assets` setting wasn't recognized by Capistrano 😞

**Comment by JasonPoll** [comment]
@chubchenko - that is exactly what I did, even with `cap doctor` saying `:keep_assets` isn't a recognized command, it does [still have an effect](https://github.com/capistrano/rails/blob/6f1dea24f9ee02017289f4af35c2a7b560a1b905/lib/capistrano/tasks/assets.rake#L33) during the deploy. 

I just went with this in my `deploy.rb`: 

``` ruby 
set :keep_assets, -> { fetch(:keep_releases, 5) }
```

**Comment by chubchenko** [comment]
@JasonPoll Thank you! I did similar to what you suggested, but my point was that after you assign a value for "keep assets" it will still display it as not recognized.

**Comment by chubchenko** [comment]
Need to assign a default value, then Capistrano will recognize it.
