### ISSUE TITLE
Support for propshaft

### ISSUE THREAD

**Issue by jcoyne** [capistrano/rails#257]
Similar to #235, when using propshaft rather than sprockets 

the `deploy:assets:backup_manifest` task fails because propshaft makes a manifest named: `public/assets/.manifest.json` which does not match the existing patterns in `:assets_manifests`

**Comment by mattbrictson** [comment]
@jcoyne can you help me understand what supporting propshaft would entail? Is this a matter of updating the capistrano-rails REAMDE with some guidance on what value propshaft users should use for `:assets_manifests`, or is it a more fundamental code change?

**Comment by jcoyne** [comment]
@mattbrictson I imaging it would just add a new pattern that matches the manifest that Propshaft uses:
 https://github.com/rails/propshaft/blob/793a20e74201cd6c97f22fb8df75f353e7aebe5b/lib/propshaft/processor.rb#L4

**Comment by jcoyne** [comment]
I've done this and it works as a workaround:
```ruby
set :assets_manifests, -> {
    [release_path.join("public", fetch(:assets_prefix), '.manifest.json')]
}
```

But now that propshaft is included by Rails, it makes sense to make this a default part of capistrano-rails.

**Comment by HLFH** [comment]
I have set 

```
set :assets_manifests, -> {
    [release_path.join("public", fetch(:assets_prefix), '.manifest.json')]
}
``` as advised in `config/deploy.rb`.

And this works well with `propshaft`.

**Comment by taketo1113** [comment]
I created PR (#265), which adds the Propshaft manifest file (`.manifest.json`) to `assets_manifests`, because Propshaft has become the default asset pipeline in Rails 8.0.
