### ISSUE TITLE
Deprecated method 'exists?' for File:Class in ruby 3.2.0

### ISSUE THREAD

**Issue by OleStan** [capistrano/rails#260]
On ruby 3.2.0 method `exists?` is removed, and now command such `cap production config:init` return error
```
cap aborted!
NoMethodError: undefined method `exists?' for File:Class
```

---

### Steps to reproduce

1. Set project ruby version 3.2.0
2. Setup Capistrano
3. try to use command `cap production config:init` 

### System configuration
Ruby 3.2.0
Capistrano 3.17.1
rails 7.0.4

**Comment by mattbrictson** [comment]
I don't think the `exists?` is used anywhere in this repo. I see you are running a task named `config:init`, but that isn't something that comes with Capistrano out of the box, and not a task that I am familiar with. Are you using a plugin that provides this task? If so, I recommend that you log the issue with the project that is responsible for that plugin.
