### ISSUE TITLE
`cap doctor` erroneously reports that `:keep_assets` is an unrecognized setting

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/rails#262]
As identified by @JasonPoll in https://github.com/capistrano/rails/issues/251#issuecomment-1613836805

**Comment by JasonPoll** [comment]
@mattbrictson are you going to work on this?  If correcting this is simply a matter of setting `:keep_assets` in `lib/capistrano/tasks/assets.rake`, I can put up a quick pull request.

**Comment by mattbrictson** [comment]
@JasonPoll yes, if you want to put a PR, I'd appreciate it! I think you're right: `:keep_assets` needs a default value (`nil` should work).

**Comment by JasonPoll** [comment]
Will do. I was about to suggest having `:keep_assets` default to the value of `:keep_releases`, but having thought more on it, I agree - `nil` is the appropriate default, and it aligns with what is currently noted as the default in the `README.md`.

**Comment by mattbrictson** [comment]
Closed via #263
