### ISSUE TITLE
support a task for db:seed

### ISSUE THREAD

**Issue by dei79** [capistrano/rails#42]
Hi,

I would like to see the following task as part of the gem

``` ruby
task :seed do
    on primary fetch(:migration_role) do
      within release_path do
        with rails_env: fetch(:rails_env)  do
          execute :rake, 'db:seed'
        end
      end
    end
  end
```

It would allow me to seed databases out of the box via capistrano

**Comment by tymat** [comment]
"Seeding is only done in deployment" is a presumptuous thing to say.  How would you expect to populate a production/staging databases with things like zip codes, products, user roles, country lists, area codes, and all sorts of things that many web applications need?

**Comment by AlexVentura** [comment]
I also seed an Admin user managed by `Devise` which then uses [Devise Invitable](https://github.com/scambra/devise_invitable) to create any other, since I don't have an Admin registrations form. So, I need `rake db:seed` in Capistrano for production ENV.
