### ISSUE TITLE
Handling rails_relative_url_root

### ISSUE THREAD

**Issue by signedbyte** [capistrano/rails#51]
Is there any reason I shouldn't put together a pull request adding an option to set the rails_relative_url_root. I'm overriding the task to do it now (not fun doing that in rake btw.) I was thinking about just setting a variable like this would do it:

In your file, do this:
``` ruby
set(:rails_relative_url_root, '/app_name')
```

Let the plugin do this:
``` ruby
 namespace :assets do
    task :precompile do
      on roles(fetch(:assets_roles)) do
        within release_path do
          with rails_env: fetch(:rails_env), rails_relative_url_root: fetch(:rails_relative_url_root): do
            execute :rake, "assets:precompile"
          end
        end
      end
    end
```

I don't believe having and empty param will do anything harmful.

**Comment by will-in-wi** [comment]
Is this still an issue?

**Comment by mattbrictson** [comment]
I prefer the `:default_env` solution that was [suggested above](https://github.com/capistrano/rails/issues/51#issuecomment-36722378). I don't think we need a special setting for this edge case.
