### ISSUE TITLE
public/assets not symlinked if :linked_dirs set by deploy.rb

### ISSUE THREAD

**Issue by mhw** [capistrano/rails#52]
#30 changed the point in capistrano's execution where `:linked_dirs` is set to a value that includes `public/assets`. It is now set in the `load:defaults` task, which `lib/capistrano/setup.rb` invokes before loading `deploy.rb`. So if `deploy.rb` contains a line saying

```
set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system}
```

as per the `deploy.rb` template, it will overwrite the system's definition and `:linked_dirs` will not include `public/assets`. This seems like a regression compared to previous behaviour.

**Comment by frangeris** [comment]
+1 same here...

**Comment by kirs** [comment]
@frangeris please, read the discussion above and have a look on the commit to capistrano fixing the issue.
