### ISSUE TITLE
Asset touch optimization

### ISSUE THREAD

**Issue by kirs** [capistrano/rails#53]
As @whitequark wrote, current asset timestamps normalization is not optimized:

``` ruby
execute :find, "#{assets} -exec touch -t #{asset_timestamp} {} ';'; true"
```

Instead of doing dozens of touches, it's possible to do just one with file list in arguments, for example

``` ruby
touch `find assets`
```

**Comment by will-in-wi** [comment]
Is this still an issue?

**Comment by mattbrictson** [comment]
Closing due to a lack of activity.
