### ISSUE TITLE
log migrations output with the info log level

### ISSUE THREAD

**Issue by betelgeuse** [capistrano/rails#54]
Currently rake db:migrate output is only shown when the debug log level is on. I think which migrations actually get run and what changes they do is important enough to be logged with at least the info level.

**Comment by erikhansen** [comment]
+1 for being able to change log_level for different tasks.

**Comment by mattbrictson** [comment]
Have you tried [Airbrussh](https://github.com/mattbrictson/airbrussh) formatter? It doesn't do different log levels per task, but it does mute `test` commands entirely, which makes the output much less noisy. Airbrussh will soon be the default formatter for Capistrano (it is already merged into master), but you can install it now by adding it to your Gemfile and Capfile.

**Comment by jaredbeck** [comment]
> Have you tried Airbrussh formatter?

I'm using airbrussh and I don't see any output from migrations:

```
00:10 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:11 deploy:migrating
      01 bundle exec rake db:migrate
    ✔ 01 redacted@redacted.com 8.306s
```

I see it took 8s, so I know something happened, but I'd still like to see the migration output. Currently, I have set `command_output: false`. Is it all-or-nothing? e.g. you see all stdout or you see none?

**Comment by mattbrictson** [comment]
> Is it all-or-nothing? e.g. you see all stdout or you see none?

Yes, that is correct.

**Comment by will-in-wi** [comment]
If setting log_level on a per task basis is desired, this should probably be opened on Capistrano proper. Closing the Capistrano::Rails ticket.
