### ISSUE TITLE
assets:precompile freezes after 10 minutes

### ISSUE THREAD

**Issue by lukaszsliwa** [capistrano/rails#55]
I have a problem with `assets:precompile`. It freezes after 10 minutes of precompiling assets. Process ends but it still waits for something and no response given.

``` ruby
INFO [2fc05e34] Running ~/.rvm/bin/rvm 2.0.0-p247@apptamers do bundle exec rake assets:precompile on x12s2.staging.apptamers.com
DEBUG [2fc05e34] Command: cd /home/webservice/project/20140129075713 && ( RAILS_ENV=production ~/.rvm/bin/rvm 2.0.0-p247@apptamers do bundle exec rake assets:precompile )
DEBUG [2fc05e34]    /home/webservice/.rvm/rubies/ruby-2.0.0-p247/bin/ruby /home/webservice/project/shared/bundle/ruby/2.0.0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets

```

CPU is 100% usage but it's normal when I precompile assets on this server.

I have set up `ssh_config` entries to make sure that it's not a `ssh` problem. So it's not a timeout problem.

```
$ cat ~/.ssh/config 
Host *
   ServerAliveInterval 15
```

I wonder if it's not a `sshkit` problem and maybe someone has the same issue.

```
capistrano-rails 1.1.0
capistrano       3.0.1
sshkit           1.3.0
```

When I do `CTR+C` after `1h`, i get:

```
/home/user/.rvm/gems/ruby-2.0.0-p247@apptamers/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:15:in `join'
/home/user/.rvm/gems/ruby-2.0.0-p247@apptamers/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:15:in `map'
/home/user/.rvm/gems/ruby-2.0.0-p247@apptamers/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:15:in `execute'
/home/user/.rvm/gems/ruby-2.0.0-p247@apptamers/gems/sshkit-1.3.0/lib/sshkit/coordinator.rb:21:in `each'
/home/user/.rvm/gems/ruby-2.0.0-p247@apptamers/gems/sshkit-1.3.0/lib/sshkit/dsl.rb:8:in `on'
/home/user/.rvm/gems/ruby-2.0.0-p247@apptamers/gems/capistrano-rails-1.1.0/lib/capistrano/tasks/assets.rake:60:in `block (3 levels) in <top (required)>'
...
```

This `runners/parallel.rb` looks interesting, maybe this is a `sshkit` runner problem?

**Comment by AlfredoRoca** [comment]
In my case, assets precompilation failed (using both capistrano3 and mina-deploy) due to not enough memory. I realize that free memory almost went to 0 and I hadn't any swap file/partition. Then, I added a swap file and It began to work fine.

**Comment by yanaizmene** [comment]
Having same problem but not only on precompile stage but for every thing that took some time to finish and outputs nothing. For example bundle install.

![image](https://cloud.githubusercontent.com/assets/7516077/14254872/4eb64d90-fa9a-11e5-856b-989626278279.png)

Now have the same problem with rubber, when task rubber:bootstrap tries to install packages.

I'm deploying from OS X yosemite to ubuntu 14.04 x64 on digital ocean.

ClientAliveInterval 30 and ClientAliveCountMax 10 didn't solve the problem.

**Comment by zx1986** [comment]
I got this issue too.
But it happened sometimes, not every time, weird.
Ran with in docker container, it goes ok on the another machine (totally the same VM).

```
root@1dbae00efbef:/home/app# rake RAILS_ENV=production assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile    <= sometimes half here for 70 sec above.


** Invoke ckeditor:nondigest (first_time)
** Invoke environment
** Execute ckeditor:nondigest
** Invoke ckeditor:nondigest
```

I just can't dump the details logs :-(

**Comment by lukaszsliwa** [comment]
One of the possible reason why it happens, is server limitations like less RAM. Once it happened the process is killed by the system.

**Comment by vedant1811** [comment]
Adding the `keepalive` config helped me. Solved the issue so far.

**Comment by rubinsh** [comment]
@lukaszsliwa - Thanks - your solution of adding  
`config.assets.logger = Logger.new $stdout`  to production.rb
worked for me!

**Comment by will-in-wi** [comment]
It sounds like there is a workaround for these situations. Closing.
