### ISSUE TITLE
Handling override of 'after' calls

### ISSUE THREAD

**Issue by signedbyte** [capistrano/rails#60]
The committers have been pretty clear on how they feel about having sub directories for root of rails apps (See: capistrano/capistrano#615) so I've gone down the path of deleting tasks from the @tasks variable and replacing them with my own which is all works fine until you get to deploy:migrate (a capistrano/rails gem.) I went to do my normal delete and replace and no matter what I did, the capistrano/rails migrate call was used. After hours of digging I figured out that when I delete the task from the @tasks, it does not live there (silently doesn't delete annoyingly enough) since the after call is implemented using the @actions list. The @actions list is a list of procs with the same line as the src location and no other obvious way to identify the proc because of the dsl wrapper.

Is there a way that anyone proposes removing/replacing that proc besides guessing at the index till the right one goes away? I have a polyglot program and don't have the luxury of having rails at the root. I'd propose a patch to support the subdir but after the previous one was closed I think that'd be the wrong direction. Thanks for the help, and a great project.

**Comment by will-in-wi** [comment]
Is this still an issue?

**Comment by mattbrictson** [comment]
Closing because this is very old. If it is still a desired feature, please open a corresponding issue in the Capistrano repo.
