### ISSUE TITLE
Deploy:restart should be default again

### ISSUE THREAD

**Issue by brodock** [capistrano/rails#67]
After 3.1.0 changes https://github.com/capistrano/capistrano/issues/925 deploy.restart was not issued by default, because of PHP and others. But Rails do require restart on each deploy, so it makes sense for this gem to add the after task back again.

**Comment by betesh** [comment]
@brodock  Add capistrano-passenger to your Gemfile.  A lot of confusion was created because capistrano 2.0 considered `touch tmp/restart.txt` as a Rails deployment task, when in fact it has nothing to do with Rails and is really a passenger task.  Hence, in capistrano 3, it has its own gem.

**Comment by brodock** [comment]
@betesh makes sense to me. Thanks!

**Comment by Kriechi** [comment]
@leehambley is https://github.com/capistrano/passenger now the official repo?
Or does @betesh still claim ownership over at https://github.com/betesh/capistrano-passenger?

Could you maybe clarify and enable the issue tracker on the official repo.
Thanks very much!

**Comment by leehambley** [comment]
https://github.com/capistrano/passenger is canonical as far as I recall.

**Comment by betesh** [comment]
Does anyone know if I can safely delete betesh/capistrano-passenger if capistrano/passenger was forked from it?

**Comment by betesh** [comment]
Or would we have to delete capistrano/passenger and then transfer ownership?

**Comment by Kriechi** [comment]
@betesh deleting your own repo should be pretty safe:
https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/

**Comment by leehambley** [comment]
You can safely delete it, or we can ask GH to mark cap/passenger as
canonical fork

**Comment by betesh** [comment]
Let's change the canonical fork.  I just sent a request to Github support asking to do that.

**Comment by betesh** [comment]
Canonical fork is now capistrano/passenger.

**Comment by Kriechi** [comment]
Great - thanks!

**Comment by leehambley** [comment]
Thanks for taking care of that chaps!
