### ISSUE TITLE
Manifest file with a multi-server setup

### ISSUE THREAD

**Issue by bruno-** [capistrano/rails#89]
Thank you for all the good work on this gem.

I'm using [capistrano-unicorn-nginx](https://github.com/capistrano-plugins/capistrano-unicorn-nginx) for deployment to multiple servers: 1 web + 2 app + 1db on digital ocean.
- With no configuration what-so-ever, assets are nicely pre-compiled on the `web` node.
- Unfortunately, the manifest file is not automatically copied/transferred from `web` to `app` servers so unicorn is not aware of the assets. As a result generated references to javascript and css files do not contain md5 hashes and those files are not served.
- I fixed the problem by manually copying manifest file from the `web` to `app` nodes (as shown in [this stackoverflow answer](http://stackoverflow.com/a/19393049/777337)) and restarting the unicorn processes. Everything works great now.

I searched through all the issues in this project and noone seems to have this problem. Is it me doing something wrong or people are using some other strategy for this?

If the above described approach is good, would you consider accepting a pull req with a task that automates that for multi-server setup?

**Comment by toobulkeh** [comment]
:+1: for some solution to this problem out of the box. I like @bruno-'s solution of moving assets around... but I agree that it should be hosted by the web box since all it's doing is nginx forwarding.

**Comment by lonre** [comment]
@bruno- Any farther updates for this? we need this :)
