### ISSUE TITLE
Assets manifest backup fails if manifests folder exists

### ISSUE THREAD

**Issue by taratatach** [capistrano/rails#91]
In `lib / capistrano / tasks / assets.rake` line `69`, the task tries to cp `manifest*` to the backup file `assets_manifest_backup`.

This will fail for projects having a `manifests` folder in `app / assets / javascripts` (I suppose the same happens if the folder is in stylesheets) with:

> Tasks: TOP => deploy:assets:backup_manifest
> (See full trace by running task with --trace)
> The deploy has failed with an error: #<SSHKit::Runner::ExecuteError: Exception while executing on host xxx.xxx.xxx.xxx: cp exit status: 1
> cp stdout: Nothing written
> cp stderr: cp: target ‘/home/deploy/xxxx/releases/20141114002603/assets_manifest_backup’ is not a directory

**Comment by asvechkar** [comment]
I have same trouble:

DEBUG [dc4856a5] Command: cd /var/www/artm/releases/20150710231625 && /usr/bin/env mkdir -p /var/www/artm/releases/20150710231625/assets_manifest_backup
DEBUG [dc4856a5]        mkdir: cannot create directory ‘/var/www/artm/releases/20150710231625/assets_manifest_backup’: File exists
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@62.76.191.109: mkdir exit status: 1
mkdir stdout: mkdir: cannot create directory ‘/var/www/artm/releases/20150710231625/assets_manifest_backup’: File exists
mkdir stderr: Nothing written

SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: mkdir: cannot create directory ‘/var/www/artm/releases/20150710231625/assets_manifest_backup’: File exists
mkdir stderr: Nothing written

Tasks: TOP => deploy:assets:backup_manifest
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@62.76.191.109: mkdir exit status: 1
mkdir stdout: mkdir: cannot create directory ‘/var/www/artm/releases/20150710231625/assets_manifest_backup’: File exists
mkdir stderr: Nothing written

I have latest capistrano, rails 4.2.0

Help me, plz

**Comment by w3villa-ankit** [comment]
??
