### ISSUE TITLE
Roles filter for migration task?

### ISSUE THREAD

**Issue by cxyokk** [capistrano/rails#97]
For example if I have one server with two roles:
```ruby
server 'example.com', user: 'example', roles: %w{app db}, primary: true
```

How do I **deploy without running migration**? The following *won't* work:
```bash
cap production deploy ROLES=app
```
The `deploy:migrate` task is triggered, regardless of the roles filter.

Looking at `capistrano-rails`'s [code](https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/migrations.rake#L7):
```ruby
  desc 'Runs rake db:migrate if migrations are set'
  task :migrate => [:set_rails_env] do
    on primary fetch(:migration_role) do # <= here
      ...
```
It seems that the migration task uses `primary()`, which doesn't invoke roles filtering.

So:
- How do I deploy without running migration?
- Can I do it using roles filtering? (which doesn't seem possible seeing from `capistrano-rails`'s code, if I'm understanding it correctly?)

Any help is appreciated, thanks!

**Comment by shoutsid** [comment]
I currently use `primary()` to get around the filtering out deploying code to server that don't need it. Unless there is another way to do it that I do not know about.

**Comment by yoccodog** [comment]
I am encountering the same problem but in a different situation: 

I have several servers to which I want to deploy my code. I have a role that I've named `:backup` and when I try to deploy only to servers with this role the deploy fails because `deploy:migrate` is being run on all servers, not just those in `:backup`. From the log below, server 10.242.0.21 does not have the `:backup` role, yet, because `primary()` is called, `deploy:migrate` is being called for it.

Server definitions:
```
server '10.242.0.21', roles: [:app, :web, :db], user: 'rails'
...
server '10.241.0.18', roles: [:backup], user: 'rails'
```

Command and some of the log:
```
> cap --roles=backup production deploy --trace
...
** Execute deploy:migrate
DEBUG[70c36012] Running /usr/bin/env if test ! -d /home/rails/data-services/releases/20150130183311; then echo "Directory does not exist '/home/rails/data-services/releases/20150130183311'" 1>&2; false; fi on 10.242.0.21
DEBUG[70c36012] Command: if test ! -d /home/rails/data-services/releases/20150130183311; then echo "Directory does not exist '/home/rails/data-services/releases/20150130183311'" 1>&2; false; fi
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 10.242.0.21: if test ! -d /home/rails/data-services/releases/20150130183311; then echo "Directory does not exist '/home/rails/data-services/releases/20150130183311'" 1>&2; false; fi exit status: 1
...
```

Does anyone have a resolution to this?

**Comment by townsen** [comment]
@yoccodog I've tried to replicate this situation and failed - see #1213. The `on()` in the above example _does_ invoke role filtering correctly.

Can you double-check your results with the latest versions? There definitely were historic issues with these, but I believe we fixed them all.

**Comment by RobinClowers** [comment]
I had this problem on version 3.2.1, updated to 3.4 and the issue went away. This bug should be closed.

**Comment by will-in-wi** [comment]
Sounds like this is fixed. Can the ticket be closed?

**Comment by yoccodog** [comment]
Go right ahead!
